version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - pip install awscli --upgrade --user
      - echo `aws --version`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${aws_region} --no-include-email)
      - jenkins_keys_bucket=${jenkins_keys_bucket}
      - deploy_hash_dev=${deploy_hash_dev}
      - deploy_hash_stage=${deploy_hash_stage}
      - deploy_hash_prod=${deploy_hash_prod}
      - master_ecr_repo=${master_ecr_repo}
      - image_tag=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd master-image
      - aws s3 cp s3://$jenkins_keys_bucket/master.key jenkins-config/master.key
      - aws s3 cp s3://$jenkins_keys_bucket/hudson.util.Secret jenkins-config/hudson.util.Secret
      - docker build -t $master_ecr_repo:latest .
      - docker tag $master_ecr_repo:latest $master_ecr_repo:$image_tag
      - echo $master_ecr_repo:$image_tag
      - aws ssm put-parameter --name "$deploy_hash_dev" --type "String" --value "$image_tag" --overwrite
      - aws ssm put-parameter --name "$deploy_hash_stage" --type "String" --value "$image_tag" --overwrite
      - aws ssm put-parameter --name "$deploy_hash_prod" --type "String" --value "$image_tag" --overwrite
      - echo Build completed for image on `date`
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $master_ecr_repo:$image_tag
      - docker push $master_ecr_repo:latest
      
