version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - sudo apt-get update
      - pip install awscli --upgrade --user
      - echo `aws --version`
      - sudo apt-get install jq
      - echo `jq --version`
      - vpc_name=${vpc_name}
      - service_name=${service_name}
      - service_role=${service_role}
      - env_name=${env_name}
      - printenv
  build:
    commands:
      - echo Entered the build phase...
      - aws ssm get-parameter --name /$service_name/$env_name/deploy-hash >> parameter.json
      - cat parameter.json
      - repository_url=${repository_url}
      - image_tag=`jq '.Parameter.Value' parameter.json | cut -c 2-8`
      - echo $repository_url:$image_tag
      - echo Build completed on `date`
      - echo $task_name
  post_build:
    commands:
      - echo Writing image definitions file...
      - printf '[{"name":"ecs-service-name","imageUri":"%s"}]' $repository_url:$image_tag > imagedefinitions.json
      - cat imagedefinitions.json
      - sed -i "s/ecs-service-name/$service_name-$service_role-$env_name/g" imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
